## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [69]:
import pandas as pd

df = pd.read_csv('Resources/client_dataset.csv')

df.head()

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1

In [70]:
# View the column names in th
print(df.columns)

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number'],
      dtype='object')

In [71]:
# Use the describe function to gather some basic statistics
df.describe()

,client_id,order_id,order_week,order_year,unit_price,unit_cost,unit_weight,qty,line_number
count,54639.000000,5.463900e+04,54639.000000,54639.000000,54639.000000,54639.000000,54639.000000,5.463900e+04,54639.000000
mean,54837.869416,5.470190e+06,11.359139,2022.993064,136.267207,99.446073,5.004116,5.702646e+02,2.979667
std,25487.438231,2.599807e+06,7.023499,0.082997,183.873135,133.164267,5.326599,1.879552e+04,2.436320
min,10033.000000,1.000886e+06,1.000000,2022.000000,0.010000,0.010000,0.000000,0.000000e+00,0.000000
25%,33593.000000,3.196372e+06,6.000000,2023.000000,20.800000,14.840000,1.450000,3.200000e+01,1.000000
50%,53305.000000,5.496966e+06,11.000000,2023.000000,68.310000,49.890000,3.240000,6.800000e+01,3.000000
75%,78498.000000,7.733869e+06,17.000000,2023.000000,173.160000,125.570000,6.890000,1.700000e+02,5.000000
max,99984.000000,9.998480e+06,52.000000,2023.000000,1396.230000,846.270000,46.430000,3.958244e+06,9.000000

In [73]:
# Use this space to do any additional research
# and familiarize yourself with the data.
df_average=df['unit_cost'].mean()
df_average

99.4460727685353

In [74]:
# What three item categories had the most entries?

top_three_categories=df['category'].value_counts().head(3)
top_three_categories

category
consumables    23538
furniture      11915
software        8400
Name: count, dtype: int64

In [75]:
# For the category with the most entries,
# which subcategory had the most entries?
filtered_df=df[df['category']=='consumables']
top_subcategory=filtered_df['subcategory'].value_counts().idxmax()
print(top_subcategory)

bathroom supplies

In [42]:
# Which five clients had the most entries in the data?
top_five_clients=df['client_id'].value_counts().head(5)
top_five_clients

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64

In [76]:
# Store the client ids of those top 5 clients in a list.
client_ids=[]
client_ids.append(top_five_clients)
print(client_ids)

[client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64]

In [77]:
# How many total units (the qty column) did the
# client with the most entries order order?
top_client_id=df['client_id'].value_counts().idxmax()
top_client_df=df[df['client_id']==top_client_id]
total_units=top_client_df['qty'].sum()
print(total_units)

64313

## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [79]:
# Create a column that calculates the 
# subtotal for each line using the unit_price
# and the qty
df['line_subtotal']=df['unit_price']*df['qty']
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number,line_subtotal
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1,115164.00
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0,523.95
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6,527.28
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3,1056.18
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1,3902.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,UCA28532-31-0B,software,logistics,83.13,51.60,2.25,33,8,2743.29
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,EBD29277-23-7U,consumables,kitchen supplies,206.59,175.46,11.70,47,0,9709.73
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,EBD30093-55-9Z,consumables,bathroom supplies,65.66,57.31,4.16,475,6,31188.50
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,XMZ38239-49-3D,furniture,stands,1.48,1.22,18.04,112,0,165.76
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,ZCZ05589-50-5D,software,project management,3.01,1.61,2.07,1031,5,3103.31

In [82]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound
# for orders over 50 pounds and $10 per
# pound for items 50 pounds or under.
def calculate_shipping(weight):
    if weight>50:
        return weight*7
    else:
        return weight*10
df['shipping_price']=df['unit_weight'].apply(calculate_shipping)
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number,line_subtotal,shipping_price
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1,115164.00,75.0
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0,523.95,14.9
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6,527.28,16.8
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3,1056.18,12.3
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1,3902.00,464.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,UCA28532-31-0B,software,logistics,83.13,51.60,2.25,33,8,2743.29,22.5
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,EBD29277-23-7U,consumables,kitchen supplies,206.59,175.46,11.70,47,0,9709.73,117.0
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,EBD30093-55-9Z,consumables,bathroom supplies,65.66,57.31,4.16,475,6,31188.50,41.6
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,XMZ38239-49-3D,furniture,stands,1.48,1.22,18.04,112,0,165.76,180.4
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,ZCZ05589-50-5D,software,project management,3.01,1.61,2.07,1031,5,3103.31,20.7

In [83]:
# Create a column for the total price
# using the subtotal and the shipping price
# along with a sales tax of 9.25%
df['line_price']=df['line_subtotal']*df['shipping_price']
df['line_price']=df['line_price']*(1+0.0925)
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number,line_subtotal,shipping_price,line_price
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,decor,wall art,1096.80,762.71,7.50,105,1,115164.00,75.0,9.436250e+06
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,consumables,pens,24.95,15.09,1.49,21,0,523.95,14.9,8.528989e+03
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,software,project management,13.52,7.86,1.68,39,6,527.28,16.8,9.677697e+03
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,consumables,pens,36.42,24.85,1.23,29,3,1056.18,12.3,1.419268e+04
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,consumables,misc,195.10,108.17,46.43,20,1,3902.00,464.3,1.979281e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,software,logistics,83.13,51.60,2.25,33,8,2743.29,22.5,6.743350e+04
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,consumables,kitchen supplies,206.59,175.46,11.70,47,0,9709.73,117.0,1.241122e+06
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,consumables,bathroom supplies,65.66,57.31,4.16,475,6,31188.50,41.6,1.417455e+06
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,furniture,stands,1.48,1.22,18.04,112,0,165.76,180.4,3.266914e+04
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,software,project management,3.01,1.61,2.07,1031,5,3103.31,20.7,7.018058e+04

In [84]:
# Create a column for the cost
# of each line using unit cost, qty, and
# shipping price (assume the shipping cost
# is exactly what is charged to the client).
df['cost']=df['unit_cost']+df['shipping_price']+df['qty']
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,subcategory,unit_price,unit_cost,unit_weight,qty,line_number,line_subtotal,shipping_price,line_price,cost
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,wall art,1096.80,762.71,7.50,105,1,115164.00,75.0,9.436250e+06,942.71
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,pens,24.95,15.09,1.49,21,0,523.95,14.9,8.528989e+03,50.99
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,project management,13.52,7.86,1.68,39,6,527.28,16.8,9.677697e+03,63.66
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,pens,36.42,24.85,1.23,29,3,1056.18,12.3,1.419268e+04,66.15
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,misc,195.10,108.17,46.43,20,1,3902.00,464.3,1.979281e+06,592.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,logistics,83.13,51.60,2.25,33,8,2743.29,22.5,6.743350e+04,107.10
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,kitchen supplies,206.59,175.46,11.70,47,0,9709.73,117.0,1.241122e+06,339.46
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,bathroom supplies,65.66,57.31,4.16,475,6,31188.50,41.6,1.417455e+06,573.91
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,stands,1.48,1.22,18.04,112,0,165.76,180.4,3.266914e+04,293.62
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,project management,3.01,1.61,2.07,1031,5,3103.31,20.7,7.018058e+04,1053.31

In [87]:
# Create a column for the profit of
# each line using line cost and line price

df['line_profit']=df['cost']+df['line_price']
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_price,unit_cost,unit_weight,qty,line_number,line_subtotal,shipping_price,line_price,cost,line_profit
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,1096.80,762.71,7.50,105,1,115164.00,75.0,9.436250e+06,942.71,9.437193e+06
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,24.95,15.09,1.49,21,0,523.95,14.9,8.528989e+03,50.99,8.579979e+03
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,13.52,7.86,1.68,39,6,527.28,16.8,9.677697e+03,63.66,9.741357e+03
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,36.42,24.85,1.23,29,3,1056.18,12.3,1.419268e+04,66.15,1.425883e+04
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,195.10,108.17,46.43,20,1,3902.00,464.3,1.979281e+06,592.47,1.979873e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,83.13,51.60,2.25,33,8,2743.29,22.5,6.743350e+04,107.10,6.754060e+04
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,206.59,175.46,11.70,47,0,9709.73,117.0,1.241122e+06,339.46,1.241461e+06
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,65.66,57.31,4.16,475,6,31188.50,41.6,1.417455e+06,573.91,1.418029e+06
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,1.48,1.22,18.04,112,0,165.76,180.4,3.266914e+04,293.62,3.296276e+04
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,3.01,1.61,2.07,1031,5,3103.31,20.7,7.018058e+04,1053.31,7.123389e+04

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25

In [90]:
# Check your work using the totals above
order_id_list=['2742071','2173913','6128929']
expected_totals=[152811.11,162388.71,923441.25]
for order_id,expected_total in zip(order_id_list,expected_totals):
    calculated_total=df[df['order_id']==order_id]['line_subtotal'].sum()
    print(f"order ID {order_id}:calculated total={calculated_total},expected_total={expected_total}")
    print(f"Match:{calculated_total==expected_total}")

order ID 2742071:calculated total=0.0,expected_total=152811.11
Match:False
order ID 2173913:calculated total=0.0,expected_total=162388.71
Match:False
order ID 6128929:calculated total=0.0,expected_total=923441.25
Match:False

## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [92]:
# How much did each of the top 5 clients by quantity
# spend? Check your work from Part 1 for client ids.
total_by_client=df.groupby('client_id')['line_subtotal'].sum()
top_clients=total_by_client.sort_values(ascending=False).head(5)
print(top_clients)

client_id
78965    5.950470e+08
85931    2.071928e+08
38473    1.636205e+08
86721    1.015831e+08
84344    9.287183e+07
Name: line_subtotal, dtype: float64

In [94]:
# Create a summary DataFrame showing the totals for the
# for the top 5 clients with the following information:
# total units purchased, total shipping price,
# total revenue, and total profit. Sort by total profit.
summary_df = df.groupby('client_id').agg({
    'qty': 'sum',
    'shipping_price': 'sum',
    'line_price': 'sum',
    'cost': 'sum',
    'line_profit': 'sum'
}).reset_index()
summary_df = summary_df.sort_values(by='line_profit', ascending=False).head(5)
print(summary_df)

     client_id      qty  shipping_price    line_price        cost  \
585      62227   224149          4865.1  1.479242e+10   234784.34
850      86721  1010426          6154.6  1.004216e+10  1029556.88
208      30339   126683          5640.7  7.035903e+09   140842.66
840      85931   644423          2763.0  5.024904e+09   652778.40
320      38473   402770          7832.2  3.760528e+09   426474.68

      line_profit
585  1.479266e+10
850  1.004319e+10
208  7.036044e+09
840  5.025557e+09
320  3.760954e+09

In [111]:
# Format the data and rename the columns
# to names suitable for presentation.
# Currency should be in millions of dollars.

df.rename(columns={
    'shipping_price': 'shipping',
    'line_price': 'Line',
    'cost': 'Total_Cost',
    'line_profit': 'profit',
    'qty':'quantity'
}, inplace=True)
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_cost,unit_weight,quantity,line_number,line_subtotal,Shipping (in millions),Line (in millions),Total_Cost,profit,Profit (in millions)
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,762.71,7.50,105,1,115164.00,0.000075,9.436250,0.000943,9.437193e+06,9.437193
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,15.09,1.49,21,0,523.95,0.000015,0.008529,0.000051,8.579979e+03,0.008580
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,7.86,1.68,39,6,527.28,0.000017,0.009678,0.000064,9.741357e+03,0.009741
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,24.85,1.23,29,3,1056.18,0.000012,0.014193,0.000066,1.425883e+04,0.014259
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,108.17,46.43,20,1,3902.00,0.000464,1.979281,0.000592,1.979873e+06,1.979873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,51.60,2.25,33,8,2743.29,0.000023,0.067433,0.000107,6.754060e+04,0.067541
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,175.46,11.70,47,0,9709.73,0.000117,1.241122,0.000339,1.241461e+06,1.241461
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,57.31,4.16,475,6,31188.50,0.000042,1.417455,0.000574,1.418029e+06,1.418029
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,1.22,18.04,112,0,165.76,0.000180,0.032669,0.000294,3.296276e+04,0.032963
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,1.61,2.07,1031,5,3103.31,0.000021,0.070181,0.001053,7.123389e+04,0.071234

In [112]:
# Sort the updated data by "Total Profit" form highest to lowest
df_sorted = df.sort_values(by='profit', ascending=False)
print(df_sorted)

          first      last                                    job  \
12597    Jordan     Price               Local government officer
25972       Amy   Stewart              Psychologist, educational
29737   William    Savage                      Minerals surveyor
15112    Dennis   Hawkins    Social research officer, government
23929   Michele  Mcdonald  Emergency planning/management officer
...         ...       ...                                    ...
14065     David   Nichols                           Geoscientist
49063     Katie   Compton                         Dramatherapist
22529   Matthew    Orozco             Research scientist (maths)
37936  Jennifer     Lewis                Agricultural consultant
29972    Dennis   Hawkins    Social research officer, government

                       phone                            email  client_id  \
12597           687.750.2141      pricej@donaldson-garcia.com      62227
25972     979.793.4884x57205           stewartamy@francis.com      86721
29737           534.689.6772        savagewilliam@johnson.com      30339
15112  001-214-888-5838x7410      hawkins.dennis.5195@lee.com      85931
23929     435-931-4939x95137    mcdonaldm317@hess-jackson.com      38473
...                      ...                              ...        ...
14065      (316)625-8661x472         nicholsdavid@sanchez.com      80891
49063           410-659-2624       comptonkatie9635@smith.com      35902
22529   +1-259-213-7449x4333           orozcomatthew@carr.com      67407
37936             9813732574  lewis.jennifer@becker-ford.info      62566
29972  001-214-888-5838x7410      hawkins.dennis.5195@lee.com      85931

       order_id  order_date  order_week  order_year  ... unit_cost  \
12597   3989744  2023-01-23           4        2023  ...    198.38
25972   6057452  2023-03-21          12        2023  ...     73.05
29737   9375270  2023-02-14           7        2023  ...    198.38
15112   7263857  2023-03-05           9        2023  ...    183.84
23929   4594154  2023-03-02           9        2023  ...    568.06
...         ...         ...         ...         ...  ...       ...
14065   5818874  2023-03-31          13        2023  ...      0.12
49063   8118125  2023-01-09           2        2023  ...      0.12
22529   5546401  2023-05-18          20        2023  ...      0.12
37936   5131256  2023-05-17          20        2023  ...      0.12
29972   7438979  2023-03-27          13        2023  ...      0.12

      unit_weight quantity  line_number  line_subtotal  \
12597       27.51   212123            6   4.873314e+07
25972        9.22   977121            3   9.810295e+07
29737       27.51   100479            7   2.308405e+07
15112        2.21   637318            3   2.061214e+08
23929        2.25   219645            5   1.482472e+08
...           ...      ...          ...            ...
14065        0.28        9            4   1.170000e+00
49063        0.28        9            1   1.170000e+00
22529        0.28        8            0   1.040000e+00
37936        0.28        6            2   7.800000e-01
29972        0.28        1            6   1.300000e-01

       Shipping (in millions)  Line (in millions)  Total_Cost        profit  \
12597                0.000275        1.464659e+04    0.212596  1.464680e+10
25972                0.000092        9.881763e+03    0.977286  9.882740e+09
29737                0.000275        6.937835e+03    0.100952  6.937936e+09
15112                0.000022        4.976646e+03    0.637524  4.977284e+09
23929                0.000023        3.644101e+03    0.220236  3.644322e+09
...                       ...                 ...         ...           ...
14065                0.000003        3.579030e-06    0.000012  1.549903e+01
49063                0.000003        3.579030e-06    0.000012  1.549903e+01
22529                0.000003        3.181360e-06    0.000011  1.410136e+01
37936                0.000003        2.386020e-06    0.000009  1.130602e+01
29972                0.000003        3.976700e-07    0.000004  4.317670e+00

       Profit (in millions)
12597          14646.798846
25972           9882.740124
29737           6937.935792
15112           4977.283836
23929           3644.321630
...                     ...
14065              0.000015
49063              0.000015
22529              0.000014
37936              0.000011
29972              0.000004

[54639 rows x 24 columns]